local myname, ns = ...
local L = LibStub("AceLocale-3.0"):GetLocale(myname, false)

local path_meta = {__index = {
    label = "Path to treasure",
    atlas = "map-icon-SuramarDoor.tga",
    path = true,
    scale = 1.1,
}}

ns.map_spellids = {
    -- [371] = 0, -- The Jade Forest
    -- [376] = 0, -- Valley of the Four Winds
    -- [379] = 0, -- Kun-Lai Summit
    -- [388] = 0, -- Townlong Steppes
    -- [390] = 0, -- Vale of Eternal Blossoms
    -- [418] = 0, -- Krasarang Wilds
	-- [422] = 0, -- Dread Wastes
	-- [504] = 0, -- Isle of Thunder
	-- [554] = 0, -- Timeless Isle
	-- [395] = 0, -- Guo-Lai Halls
	-- [373] = 0, -- Greenstone Quarry, cave in Jade Forest

}

ns.points = {
    [371] = { -- The Jade Forest
        [26223235] = ({
            label = L["Ancient Pandaren Tea Pot"],
            cont = true,
			quest = 31400,
            Zamro = true,
            note = L["Ancient Pandaren Tea Pot Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [31962775] = ({
            label = L["Lucky Pandaren Coin"],
            cont = true,
			quest = 31401,
            Zamro = true,
            note = L["Lucky Pandaren Coin Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
		[23493505] = ({
            label = L["Pandaren Ritual Stone"],
            cont = true,
			quest = 31404,
            Zamro = true,
            note = L["Pandaren Ritual Stone Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
		[51229999] = ({
            label = L["Ship's Locker"],
            cont = true,
			quest = 31396,
            Zamro = true,
            note = L["Ship's Locker Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [24005300] = ({
            label = L["Chest of Supplies"],
            cont = true,
			quest = 31864,
            Zamro = true,
            note = L["Chest of Supplies Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),	
        [46308070] = ({
            label = L["Offering of Rememberance"],
            cont = true,
			quest = 31865,
            Zamro = true,
            note = L["Offering of Rememberance Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),		
        [62452752] = ({
            label = L["Stash of Gems"],
            cont = true,
			quest = 31866,
            Zamro = true,
            note = L["Stash of Gems Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),			
		[43407640] = ({
            label = L["Kor'nas Nightsavage"],
            cont = true,
            achievement = {id = 7439, criteria = 21069}, 
            Zamro = true,
            note = L["Kor'nas Nightsavage Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
        }),
		[39406240] = ({
            label = L["Krax'ik"],
            cont = true,
            achievement = {id = 7439, criteria = 21062}, 
            Zamro = true,
            note = L["Krax'ik Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
        }),
		[64407400] = ({
            label = L["Sarnak"],
            cont = true,
            achievement = {id = 7439, criteria = 21090}, 
            Zamro = true,
            note = L["Sarnak Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
        }),
		[42403880] = ({
            label = L["Mister Ferocious"],
            cont = true,
            achievement = {id = 7439, criteria = 21048}, 
            Zamro = true,
            note = L["Mister Ferocious Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
        }),
		[40801520] = ({
            label = L["Morgrinn Crackfang"],
            cont = true,
            achievement = {id = 7439, criteria = 21076}, 
            Zamro = true,
            note = L["Morgrinn Crackfang Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
        }),
		[33405080] = ({
            label = L["Aethis"],
            cont = true,
            achievement = {id = 7439, criteria = 21055}, 
            Zamro = true,
            note = L["Aethis Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
        }),
		[57207160] = ({
            label = L["Urobi the Walker"],
            cont = true,
            achievement = {id = 7439, criteria = 21083}, 
            Zamro = true,
            note = L["Urobi the Walker Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
        }),
        [52004460] = ({
            label = L["Ferdinand"],
            cont = true,
            achievement = {id = 7439, criteria = 21097}, 
		    Zamro = true,
            note = L["Ferdinand Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
        }),
        [57604480] = ({
            label = L["Order"],
            cont = true,
		    Zamro = true,
            note = L["Order Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\tokens.tga",
        }),	
        [53806180] = ({
            label = L["August"],
            cont = true,
		    Zamro = true,
            note = L["August Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\tokens.tga",
        }),		
		[52401880] = ({
            label = L["Zandalari Warbringer"],
            cont = true,
		    Zamro = true,
            note = L["Zandalari Warbringer Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
        }),		
        [46102920] = ({
            label = L["Ancient Pandaren Mining Pick"],
            cont = true,
			quest = 31399,
            Zamro = true,
            note = L["Ancient Pandaren Mining Pick Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\cave.tga",
        }),				
    },
		[373] = { -- Greenstone Quarry, cave in Jade Forest
	        [33107800] = ({
            label = L["Ancient Pandaren Mining Pick"],
            cont = true,
			quest = 31399,
            Zamro = true,
            note = L["Ancient Pandaren Mining Pick Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),		
        [44007050] = ({
            label = L["Ancient Pandaren Mining Pick"],
            cont = true,
			quest = 31399,
            Zamro = true,
            note = L["Ancient Pandaren Mining Pick Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),	
        [43703850] = ({
            label = L["Ancient Pandaren Mining Pick"],
            cont = true,
			quest = 31399,
            Zamro = true,
            note = L["Ancient Pandaren Mining Pick Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),	
        [38704750] = ({
            label = L["Ancient Pandaren Mining Pick"],
            cont = true,
			quest = 31399,
            Zamro = true,
            note = L["Ancient Pandaren Mining Pick Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),	
        [32606270] = ({
            label = L["Ancient Pandaren Mining Pick"],
            cont = true,
			quest = 31399,
            Zamro = true,
            note = L["Ancient Pandaren Mining Pick Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),	
        [38231394] = ({
            label = L["Ancient Pandaren Mining Pick"],
            cont = true,
			quest = 31399,
            Zamro = true,
            note = L["Ancient Pandaren Mining Pick Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),	
	},	
		[433] = { -- The Veiled Stair
        [74937648] = ({
            label = L["The Hammer of Folly"],
            cont = true,
			quest = 31428,
            Zamro = true,
            note = L["The Hammer of Folly Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
    },
	    [376] = { -- Valley of the Four Winds
        [23712833] = ({
            label = L["Virmen Treasure Cache"],
            cont = true,
			quest = 31405,
            Zamro = true,
            note = L["Virmen Treasure Cache Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [32806240] = ({
            label = L["Blackhoof"],
            cont = true,
			achievement = {id = 7439, criteria = 21098}, 
		    Zamro = true,
            note = L["Blackhoof Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
        }),
		[18407740] = ({
            label = L["Jonn-Dar"],
            cont = true,
            achievement = {id = 7439, criteria = 21077}, 			
		    Zamro = true,
            note = L["Jonn-Dar Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
        }),
		[88401800] = ({
            label = L["Nasra Spothide"],
            cont = true,
            achievement = {id = 7439, criteria = 21084}, 			
		    Zamro = true,
            note = L["Nasra Spothide Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
        }),
		[52402820] = ({
            label = L["Sele'na"],
            cont = true,
            achievement = {id = 7439, criteria = 21056}, 			
		    Zamro = true,
            note = L["Sele'na Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
        }),
		[13803860] = ({
            label = L["Bonobos"],
            cont = true,
            achievement = {id = 7439, criteria = 21049}, 			
		    Zamro = true,
            note = L["Bonobos Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
        }),
		[8005920] = ({
            label = L["Nal'lak the Ripper"],
            cont = true,
            achievement = {id = 7439, criteria = 21063}, 			
		    Zamro = true,
            note = L["Nal'lak the Ripper Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
        }),
		[67405940] = ({
            label = L["Salyin Warscout"],
            cont = true,
            achievement = {id = 7439, criteria = 21091}, 			
		    Zamro = true,
            note = L["Salyin Warscout Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
        }),
		[36802540] = ({
            label = L["Sulik'shor"],
            cont = true,
            achievement = {id = 7439, criteria = 21070}, 			
		    Zamro = true,
            note = L["Sulik'shor Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
        }),
    },
    [379] = { -- Kun-Lai Summit
        [50366177] = ({
            label = L["Hozen Treasure Cache"],
            cont = true,
			quest = 31414,
            Zamro = true,
            note = L["Hozen Treasure Cache Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
	    [59405300] = ({
            label = L["Stolen Sprite Treasure"],
            cont = true,
			quest = 31415,			
            Zamro = true,
            note = L["Stolen Sprite Treasure Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
	    }),
	    [72013396] = ({
            label = L["Statue of Xuen"],
            cont = true,
			quest = 31416,					
            Zamro = true,
            note = L["Statue of Xuen Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
	    }),
		[36707970] = ({
            label = L["Lost Adventurer's Belongings"],
            cont = true,
			quest = 31418,				
            Zamro = true,
            note = L["Lost Adventurer's Belongings Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
	    }),
		[52575154] = ({
            label = L["Rikktik's Tiny Chest"],
            cont = true,
			quest = 31419,				
            Zamro = true,
            note = L["Rikktik's Tiny Chest Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
	    }),
		[64234513] = ({
            label = L["Ancient Mogu Tablet"],
            cont = true,
			quest = 31420,				
            Zamro = true,
            note = L["Ancient Mogu Tablet Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
	    }),
		[59247303] = ({
            label = L["Terracotta Head"],
            cont = true,
			quest = 31422,				
            Zamro = true,
            note = L["Terracotta Head Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
	    }),
		[40604280] = ({
            label = L["Ahone the Wanderer"],
            cont = true,
            achievement = {id = 7439, criteria = 21086}, 			
            Zamro = true,
            note = L["Ahone the Wanderer Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[57007580] = ({
            label = L["Havak"],
            cont = true,
            achievement = {id = 7439, criteria = 21079}, 					
            Zamro = true,
            note = L["Havak Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[63801380] = ({
            label = L["Nessos the Oracle"],
            cont = true,
            achievement = {id = 7439, criteria = 21093}, 			
            Zamro = true,
            note = L["Nessos the Oracle Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[36407960] = ({
            label = L["Ski'thik"],
            cont = true,
            achievement = {id = 7439, criteria = 21065}, 			
            Zamro = true,
            note = L["Ski'thik Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[55404340] = ({
            label = L["Borginn Darkfist"],
            cont = true,
            achievement = {id = 7439, criteria = 21072}, 			
            Zamro = true,
            note = L["Borginn Darkfist Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[47408120] = ({
            label = L["Korda Torros"],
            cont = true,
            achievement = {id = 7439, criteria = 21100}, 			
            Zamro = true,
            note = L["Korda Torros Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[44806380] = ({
            label = L["Scritch"],
            cont = true,
            achievement = {id = 7439, criteria = 21051}, 			
            Zamro = true,
            note = L["Scritch Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[73007660] = ({
            label = L["Zai the Outcast"],
            cont = true,
            achievement = {id = 7439, criteria = 21058}, 				
            Zamro = true,
            note = L["Zai the Outcast Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[75006740] = ({
            label = L["Zandalari Warbringer"],
            cont = true,
		    Zamro = true,
            note = L["Zandalari Warbringer Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
        }),		
    },
    [388] = { -- Townlong Steppes
        [56406480] = ({
            label = L["Fragment of Dread"],
            cont = true,
			quest = 31423,
            Zamro = true,
            note = L["Fragment of Dread Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [36908760] = ({
            label = L["Fragment of Dread"],
            cont = true,
			quest = 31423,
            Zamro = true,
            note = L["Fragment of Dread Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [48408860] = ({
            label = L["Fragment of Dread"],
            cont = true,
			quest = 31423,
            Zamro = true,
            note = L["Fragment of Dread Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
        [64502150] = ({
            label = L["Fragment of Dread"],
            cont = true,
			quest = 31423,
            Zamro = true,
            note = L["Fragment of Dread Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),	
        [32806160] = ({
            label = L["Fragment of Dread"],
            cont = true,
			quest = 31423,
            Zamro = true,
            note = L["Fragment of Dread Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),				
	    [52845617] = ({
            label = L["Hardened Sap of Kri'vess"],
            cont = true,
			quest = 31424,			
            Zamro = true,
            note = L["Hardened Sap of Kri'vess Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
	    }),
	    [57505850] = ({
            label = L["Hardened Sap of Kri'vess"],
            cont = true,
			quest = 31424,			
            Zamro = true,
            note = L["Hardened Sap of Kri'vess Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
	    }),		
	    [65838608] = ({
            label = L["Amber Encased Moth"],
            cont = true,
			quest = 31426,					
            Zamro = true,
            note = L["Amber Encased Moth Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
	    }),
		[62823405] = ({
            label = L["Abandoned Crate of Goods"],
            cont = true,
			quest = 31427,				
            Zamro = true,
            note = L["Abandoned Crate of Goods Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
	    }),
		[67607420] = ({
            label = L["The Yowler"],
            cont = true,
            achievement = {id = 7439, criteria = 21052}, 			
            Zamro = true,
            note = L["The Yowler Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[41807860] = ({
            label = L["Lith'ik the Stalker"],
            cont = true,
            achievement = {id = 7439, criteria = 21066}, 			
            Zamro = true,
            note = L["Lith'ik the Stalker Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[62803540] = ({
            label = L["Kah'tir"],
            cont = true,
            achievement = {id = 7439, criteria = 21080}, 			
            Zamro = true,
            note = L["Kah'tir Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[59208540] = ({
            label = L["Siltriss the Sharpener"],
            cont = true,
            achievement = {id = 7439, criteria = 21094}, 			
            Zamro = true,
            note = L["Siltriss the Sharpener Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[65408740] = ({
            label = L["Eshelon"],
            cont = true,
            achievement = {id = 7439, criteria = 21059}, 			
            Zamro = true,
            note = L["Eshelon Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[53806340] = ({
            label = L["Norlaxx"],
            cont = true,
            achievement = {id = 7439, criteria = 21073}, 			
            Zamro = true,
            note = L["Norlaxx Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[32006180] = ({
            label = L["Yul Wildpaw"],
            cont = true,
            achievement = {id = 7439, criteria = 21087}, 			
            Zamro = true,
            note = L["Yul Wildpaw Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[64004940] = ({
            label = L["Lon the Bull"],
            cont = true,
            achievement = {id = 7439, criteria = 21101}, 			
            Zamro = true,
            note = L["Lon the Bull Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
        [39406200] = ({
            label = L["August"],
            cont = true,
		    Zamro = true,
            note = L["August Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\tokens.tga",
        }),		
        [49607059] = ({
            label = L["Shado"],
            cont = true,
		    Zamro = true,
            note = L["Shado Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\tokens.tga",
        }),			
		[36408540] = ({
            label = L["Zandalari Warbringer"],
            cont = true,
		    Zamro = true,
            note = L["Zandalari Warbringer Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
        }),	
		[37205760] = ({
            label = L["Huggalon the Heart Watcher"],
            cont = true,
		    Zamro = true,
            note = L["Huggalon the Heart Watcher Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
        }),			
    },
	[390] = { -- Vale of Eternal Blossoms
		[30409140] = ({
            label = L["Major Nanners"],
            cont = true,
            achievement = {id = 7439, criteria = 21054}, 			
            Zamro = true,
            note = L["Major Nanners Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[14005820] = ({
            label = L["Kal'tik the Blight"],
            cont = true,
            achievement = {id = 7439, criteria = 21068}, 			
            Zamro = true,
            note = L["Kal'tik the Blight Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[39602460] = ({
            label = L["Urgolax"],
            cont = true,
            achievement = {id = 7439, criteria = 21082}, 			
            Zamro = true,
            note = L["Urgolax Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[35205980] = ({
            label = L["Moldo One-Eye"],
            cont = true,
            achievement = {id = 7439, criteria = 21096}, 			
            Zamro = true,
            note = L["Moldo One-Eye Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[69203020] = ({
            label = L["Sahn Tidehunter"],
            cont = true,
            achievement = {id = 7439, criteria = 21061}, 			
            Zamro = true,
            note = L["Sahn Tidehunter Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[15003540] = ({
            label = L["Kang the Soul Thief"],
            cont = true,
            achievement = {id = 7439, criteria = 21075}, 			
            Zamro = true,
            note = L["Kang the Soul Thief Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[42406900] = ({
            label = L["Ai-Ran the Shifting Cloud"],
            cont = true,
            achievement = {id = 7439, criteria = 21089}, 			
            Zamro = true,
            note = L["Ai-Ran the Shifting Cloud Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[87204420] = ({
            label = L["Yorik Sharpeye"],
            cont = true,
            achievement = {id = 7439, criteria = 21103}, 			
            Zamro = true,
            note = L["Yorik Sharpeye Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),		
		[34608940] = ({
            label = L["Aetha"],
            cont = true,		
            achievement = {id = 7317, criteria = 20521}, 			
            Zamro = true,
            note = L["Aetha Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
	    }),	
		[16404780] = ({
            label = L["Bai-Jin the Butcher"],
            cont = true,		
            achievement = {id = 7317, criteria = 20530}, 			
            Zamro = true,
            note = L["Bai-Jin the Butcher Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
	    }),		
		[28404300] = ({
            label = L["Baolai the Immolator"],
            cont = true,		
            achievement = {id = 7317, criteria = 20524}, 			
            Zamro = true,
            note = L["Baolai the Immolator Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
	    }),		
		[24602670] = ({
            label = L["Bloodtip"],
            cont = true,		
            achievement = {id = 7317, criteria = 20526}, 			
            Zamro = true,
            note = L["Bloodtip Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
	    }),		
		[24602670] = ({
            label = L["Huo-Shang"],
            cont = true,		
            achievement = {id = 7317, criteria = 20529}, 			
            Zamro = true,
            note = L["Huo-Shang Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
	    }),		
		[24602670] = ({
            label = L["Gaohun the Soul-Severer"],
            cont = true,		
            achievement = {id = 7317, criteria = 20525}, 			
            Zamro = true,
            note = L["Gaohun the Soul-Severer Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
	    }),		
		[45805900] = ({
            label = L["Cracklefang"],
            cont = true,		
            achievement = {id = 7317, criteria = 20517}, 			
            Zamro = true,
            note = L["Cracklefang Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
	    }),		
		[26405040] = ({
            label = L["General Temuja"],
            cont = true,		
            achievement = {id = 7317, criteria = 20519}, 			
            Zamro = true,
            note = L["General Temuja Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
	    }),		
		[27001340] = ({
            label = L["Gochao the Ironfist"],
            cont = true,		
            achievement = {id = 7317, criteria = 20528}, 			
            Zamro = true,
            note = L["Gochao the Ironfist Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
	    }),		
		[6205780] = ({
            label = L["Kri'chon"],
            cont = true,		
            achievement = {id = 7317, criteria = 20531}, 			
            Zamro = true,
            note = L["Kri'chon Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
	    }),		
		[66203900] = ({
            label = L["Quid"],
            cont = true,		
            achievement = {id = 7317, criteria = 20522}, 			
            Zamro = true,
            note = L["Quid Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
	    }),		
		[30407800] = ({
            label = L["Shadowmaster Sydow"],
            cont = true,		
            achievement = {id = 7317, criteria = 20520}, 			
            Zamro = true,
            note = L["Shadowmaster Sydow Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
	    }),		
		[47406620] = ({
            label = L["Spirit of Lao-Fe"],
            cont = true,		
            achievement = {id = 7317, criteria = 20523}, 			
            Zamro = true,
            note = L["Spirit of Lao-Fe Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
	    }),		
		[34405140] = ({
            label = L["Vicejaw"],
            cont = true,		
            achievement = {id = 7317, criteria = 20518}, 			
            Zamro = true,
            note = L["Vicejaw Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
	    }),	
		[7803380] = ({
            label = L["Vyraxxis"],
            cont = true,		
            achievement = {id = 7317, criteria = 20532}, 			
            Zamro = true,
            note = L["Vyraxxis Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
	    }),	
		[45347624] = ({
            label = L["Wulon"],
            cont = true,		
            achievement = {id = 7317, criteria = 20527}, 			
            Zamro = true,
            note = L["Wulon Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
	    }),			
        [21607159] = ({
            label = L["Lotus"],
            cont = true,
		    Zamro = true,
            note = L["Lotus Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\tokens.tga",
        }),				
    },
		[395] = { -- Guo-Lai Halls	
		[24602670] = ({
            label = L["Bloodtip"],
            cont = true,		
            achievement = {id = 7317, criteria = 20526}, 			
            Zamro = true,
            note = L["Bloodtip Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
	    }),		
		[64041911] = ({
            label = L["Huo-Shang"],
            cont = true,		
            achievement = {id = 7317, criteria = 20529}, 			
            Zamro = true,
            note = L["Huo-Shang Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
	    }),		
		[24602670] = ({
            label = L["Gaohun the Soul-Severer"],
            cont = true,		
            achievement = {id = 7317, criteria = 20525}, 			
            Zamro = true,
            note = L["Gaohun the Soul-Severer Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
        }),				
    },
	[418] = { -- Krasarang Wilds
        [71000920] = ({
            label = L["Saurok Stone Tablet"],
			quest = 31408,			
            cont = true,
            Zamro = true,
            note = L["Saurok Stone Tablet Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
        }),
	    [56204680] = ({
            label = L["Arness the Scale"],
            cont = true,
            achievement = {id = 7439, criteria = 21092}, 	
            Zamro = true,
            note = L["Arness the Scale Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
	    [53403860] = ({
            label = L["Gaarn the Toxic"],
            cont = true,
            achievement = {id = 7439, criteria = 21071}, 	
            Zamro = true,
            note = L["Gaarn the Toxic Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
	    [67202300] = ({
            label = L["Qu'nas"],
            cont = true,
            achievement = {id = 7439, criteria = 21078}, 	
            Zamro = true,
            note = L["Qu'nas Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
	    [51808900] = ({
            label = L["Spriggin"],
            cont = true,
            achievement = {id = 7439, criteria = 21050}, 	
            Zamro = true,
            note = L["Spriggin Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
	    [30603820] = ({
            label = L["Cournith Waterstrider"],
            cont = true,
            achievement = {id = 7439, criteria = 21057}, 	
            Zamro = true,
            note = L["Cournith Waterstrider Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
	    [39402880] = ({
            label = L["Go-Kan"],
            cont = true,
            achievement = {id = 7439, criteria = 21099}, 	
            Zamro = true,
            note = L["Go-Kan Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
	    [39405520] = ({
            label = L["Ruun Ghostpaw"],
            cont = true,
            achievement = {id = 7439, criteria = 21085}, 	
            Zamro = true,
            note = L["Ruun Ghostpaw Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
	    [14403540] = ({
            label = L["Torik-Ethis"],
            cont = true,
            achievement = {id = 7439, criteria = 21064}, 	
            Zamro = true,
            note = L["Torik-Ethis Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),		
	    [84802720] = ({
            label = L["Dalan Nightbreaker"],
            cont = true,
            achievement = {id = 19999, criteria = 65595}, 	
            Zamro = true,
            note = L["Dalan Nightbreaker Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
	    }),
	    [87402920] = ({
            label = L["Disha Fearwarden"],
            cont = true,
            achievement = {id = 19999, criteria = 65596}, 	
            Zamro = true,
            note = L["Disha Fearwarden Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
	    }),
	    [13605700] = ({
            label = L["Kar Warmaker"],
            cont = true,
            achievement = {id = 19999, criteria = 65599}, 	
            Zamro = true,
            note = L["Kar Warmaker Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
	    }),
	    [84403100] = ({
            label = L["Mavis Harms"],
            cont = true,
            achievement = {id = 19999, criteria = 65600}, 	
            Zamro = true,
            note = L["Mavis Harms Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
	    }),
	    [10605660] = ({
            label = L["Muerta"],
            cont = true,
            achievement = {id = 19999, criteria = 65601}, 	
            Zamro = true,
            note = L["Muerta Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
	    }),
	    [13006660] = ({
            label = L["Ubunti the Shade"],
            cont = true,
            achievement = {id = 19999, criteria = 65606}, 	
            Zamro = true,
            note = L["Ubunti the Shade Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
	    }),	
        [31206340] = ({
            label = L["August"],
            cont = true,
		    Zamro = true,
            note = L["August Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\tokens.tga",
        }),		
        [68404340] = ({
            label = L["Anglers"],
            cont = true,
		    Zamro = true,
            note = L["Anglers Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\tokens.tga",
        }),	
        [89603260] = ({
            label = L["Alliance"],
            cont = true,
		    Zamro = true,
            note = L["Alliance Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\tokens.tga",
        }),	
        [10405380] = ({
            label = L["Horde"],
            cont = true,
		    Zamro = true,
            note = L["Horde Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\tokens.tga",
        }),		
        [39866578] = ({
            label = L["Zandalari Warbringer"],
            cont = true,
		    Zamro = true,
            note = L["Zandalari Warbringer Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
        }),				
    },
    [422] = { -- Dread Wastes
	    [55206380] = ({
            label = L["Ik-Ik the Nimble"],
            cont = true,
            achievement = {id = 7439, criteria = 21053}, 	
            Zamro = true,
            note = L["Ik-Ik the Nimble Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
	    [35603060] = ({
            label = L["Gar'lok"],
            cont = true,
            achievement = {id = 7439, criteria = 21067}, 	
            Zamro = true,
            note = L["Gar'lok Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
	    [73002220] = ({
            label = L["Krol the Blade"],
            cont = true,
            achievement = {id = 7439, criteria = 21081}, 	
            Zamro = true,
            note = L["Krol the Blade Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
	    [36006260] = ({
            label = L["Omnis Grinlok"],
            cont = true,
            achievement = {id = 7439, criteria = 21095}, 	
            Zamro = true,
            note = L["Omnis Grinlok Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
	    [64005860] = ({
            label = L["Nalash Verdantis"],
            cont = true,
            achievement = {id = 7439, criteria = 21060}, 	
            Zamro = true,
            note = L["Nalash Verdantis Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
	    [71803740] = ({
            label = L["Karr the Darkener"],
            cont = true,
            achievement = {id = 7439, criteria = 21074}, 	
            Zamro = true,
            note = L["Karr the Darkener Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
	    [34802300] = ({
            label = L["Ai-Li Skymirror"],
            cont = true,
            achievement = {id = 7439, criteria = 21088}, 	
            Zamro = true,
            note = L["Ai-Li Skymirror Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
	    [25002860] = ({
            label = L["Dak the Breaker"],
            cont = true,
            achievement = {id = 7439, criteria = 21102}, 	
            Zamro = true,
            note = L["Dak the Breaker Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),	
        [55003579] = ({
            label = L["Klaxxi"],
            cont = true,
		    Zamro = true,
            note = L["Klaxxi Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\tokens.tga",
        }),		
        [47206140] = ({
            label = L["Zandalari Warbringer"],
            cont = true,
		    Zamro = true,
            note = L["Zandalari Warbringer Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",
        }),				
    },
    [504] = { -- Isle of Thunder
	    [39408140] = ({
            label = L["Ra'sha"],
            cont = true,
            achievement = {id = 20000, criteria = 65631}, 	
            Zamro = true,
            note = L["Ra'sha Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),	
		[61404940] = ({
            label = L["God-Hulk Ramuk"],
            cont = true,
            achievement = {id = 20000, criteria = 65632}, 			
            Zamro = true,
            note = L["God-Hulk Ramuk Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[53605300] = ({
            label = L["Goda"],
            cont = true,
            achievement = {id = 20000, criteria = 65633}, 			
            Zamro = true,
            note = L["Goda Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[48022565] = ({
            label = L["Backbreaker Uru"],
            cont = true,
            achievement = {id = 20000, criteria = 65634}, 			
            Zamro = true,
            note = L["Backbreaker Uru Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[54403560] = ({
            label = L["Lu-Ban"],
            cont = true,
            achievement = {id = 20000, criteria = 65635}, 			
            Zamro = true,
            note = L["Lu-Ban Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[35006220] = ({
            label = L["Mumta"],
            cont = true,
            achievement = {id = 20000, criteria = 65636}, 			
            Zamro = true,
            note = L["Mumta Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[50407220] = ({
            label = L["Progenitus"],
            cont = true,
            achievement = {id = 20000, criteria = 65637}, 			
            Zamro = true,
            note = L["Progenitus Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[33408080] = ({
            label = L["Ku'lai the Skyclaw"],
            cont = true,
            achievement = {id = 20000, criteria = 65638}, 			
            Zamro = true,
            note = L["Ku'lai the Skyclaw Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[44603000] = ({
            label = L["Al'tabim the All-Seeing"],
            cont = true,
            achievement = {id = 20000, criteria = 65639}, 			
            Zamro = true,
            note = L["Al'tabim the All-Seeing Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[63444916] = ({
            label = L["Molthor"],
            cont = true,
            achievement = {id = 20000, criteria = 65640}, 			
            Zamro = true,
            note = L["Molthor Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[48208700] = ({
            label = L["Haywire Sunreaver Construct"],
            cont = true,
            achievement = {id = 20000, criteria = 65641}, 			
            Zamro = true,
            note = L["Haywire Sunreaver Construct Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),		
    },
	[554] = { -- Timeless Isle
        [68406040] = ({
            label = L["Flameheart Shawl"],
            achievement = {id = 19982, criteria = 65819}, 		
            cont = true,
            Zamro = true,
            note = L["Flameheart Shawl Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",	
	    }),
	    [68406040] = ({
            label = L["Riverspeaker's Trident"],
            cont = true,
            achievement = {id = 19982, criteria = 65820}, 					
            Zamro = true,
            note = L["Riverspeaker's Trident Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
	    }),
	    [68406040] = ({
            label = L["Cloudstrike Family Helm"],
            cont = true,
            achievement = {id = 19982, criteria = 65821}, 				
            Zamro = true,
            note = L["Cloudstrike Family Helm Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
	    }),
	    [68406040] = ({
            label = L["Snowdrift Tiger Talons"],
            cont = true,
            achievement = {id = 19982, criteria = 65822}, 				
            Zamro = true,
            note = L["Snowdrift Tiger Talons Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
	    }),
	    [49706940] = ({
            label = L["Gleaming Treasure Chest"],
            cont = true,
			quest = 32969,					
            Zamro = true,
            note = L["Gleaming Treasure Chest Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
	    }),
	    [54004720] = ({
            label = L["Rope-Bound Treasure Chest"],
            cont = true,
			quest = 32968,					
            Zamro = true,
            note = L["Rope-Bound Treasure Chest Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
	    }),
	    [58706010] = ({
            label = L["Mist-Covered Treasure Chest"],
            cont = true,
			quest = 32971,					
            Zamro = true,
            note = L["Mist-Covered Treasure Chest Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
	    }),
	    [40009200] = ({
            label = L["Sunken Treasure"],
            cont = true,
			quest = 32957,					
            Zamro = true,
            note = L["Sunken Treasure Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
	    }),
	    [17205730] = ({
            label = L["Blackguard's Jetsam"],
            cont = true,
			quest = 32956,					
            Zamro = true,
            note = L["Blackguard's Jetsam Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",
	    }),
	    [71308000] = ({
            label = L["Gleaming Treasure Satchel"],
            cont = true,
			quest = 32970,					
            Zamro = true,
            note = L["Gleaming Treasure Satchel Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\chest.tga",	
	    }),
		[44003720] = ({
            label = L["Jadefire"],
            cont = true,
            achievement = {id = 20001, criteria = 65661}, 			
            Zamro = true,
            note = L["Jadefire Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[60208740] = ({
            label = L["Rattleskew"],
            cont = true,
            achievement = {id = 20001, criteria = 65662}, 			
            Zamro = true,
            note = L["Rattleskew Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[43606940] = ({
            label = L["Cranegnasher"],
            cont = true,
            achievement = {id = 20001, criteria = 65665}, 			
            Zamro = true,
            note = L["Cranegnasher Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[58004860] = ({
            label = L["Spelurk"],
            cont = true,
            achievement = {id = 20001, criteria = 65666}, 			
            Zamro = true,
            note = L["Spelurk Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[63444916] = ({
            label = L["Cah Silentsky"],
            cont = true,
            achievement = {id = 20001, criteria = 65667}, 			
            Zamro = true,
            note = L["Cah Silentsky Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[25203540] = ({
            label = L["Chelon"],
            cont = true,
            achievement = {id = 20001, criteria = 65668}, 			
            Zamro = true,
            note = L["Chelon Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[33608540] = ({
            label = L["Karkanos"],
            cont = true,
            achievement = {id = 20001, criteria = 65669}, 			
            Zamro = true,
            note = L["Karkanos Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[37207700] = ({
            label = L["Zhu-Gon the Sour"],
            cont = true,
            achievement = {id = 20001, criteria = 65670}, 			
            Zamro = true,
            note = L["Zhu-Gon the Sour Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[40208280] = ({
            label = L["Gu'chi the Swarmbringer"],
            cont = true,
            achievement = {id = 20001, criteria = 65672}, 			
            Zamro = true,
            note = L["Gu'chi the Swarmbringer Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[47008740] = ({
            label = L["Zesqua"],
            cont = true,
            achievement = {id = 20001, criteria = 65671}, 			
            Zamro = true,
            note = L["Zesqua Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",
	    }),
		[30805060] = ({
            label = L["Emerald Gander"],
            cont = true,
            achievement = {id = 20001, criteria = 65673}, 			
            Zamro = true,
            note = L["Emerald Gander Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",		
	    }),
		[23604980] = ({
            label = L["Great Turtle Furyshell"],
            cont = true,
            achievement = {id = 20001, criteria = 65674}, 			
            Zamro = true,
            note = L["Great Turtle Furyshell Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",	
	    }),
		[67404380] = ({
            label = L["Leafmender"],
            cont = true,
            achievement = {id = 20001, criteria = 65675}, 			
            Zamro = true,
            note = L["Leafmender Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",	
	    }),
		[31805840] = ({
            label = L["Ironfur Steelhorn"],
            cont = true,
            achievement = {id = 20001, criteria = 65676}, 			
            Zamro = true,
            note = L["Ironfur Steelhorn Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\bskull.tga",				
	    }),		
		[44003920] = ({
            label = L["Rock Moss"],
            cont = true,
            achievement = {id = 20002, criteria = 65642}, 			
            Zamro = true,
            note = L["Rock Moss Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",	
	    }),	
		[54005240] = ({
            label = L["Cinderfall"],
            cont = true,
            achievement = {id = 20002, criteria = 65643}, 			
            Zamro = true,
            note = L["Cinderfall Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",	
	    }),		
		[71208220] = ({
            label = L["Stinkbraid"],
            cont = true,
            achievement = {id = 20002, criteria = 65644}, 			
            Zamro = true,
            note = L["Stinkbraid Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",	
	    }),		
		[64202860] = ({
            label = L["Garnia"],
            cont = true,
            achievement = {id = 20002, criteria = 65645}, 			
            Zamro = true,
            note = L["Garnia Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",	
	    }),		
		[54004220] = ({
            label = L["Tsavo'ka"],
            cont = true,
            achievement = {id = 20002, criteria = 65646}, 			
            Zamro = true,
            note = L["Tsavo'ka Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",	
	    }),		
		[65505730] = ({
            label = L["Huolon"],
            cont = true,
            achievement = {id = 20002, criteria = 65647}, 			
            Zamro = true,
            note = L["Huolon Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",	
	    }),		
		[18805460] = ({
            label = L["Monstrous Spineclaw"],
            cont = true,
            achievement = {id = 20002, criteria = 65648}, 			
            Zamro = true,
            note = L["Monstrous Spineclaw Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",	
	    }),		
		[63737281] = ({
            label = L["Bufo"],
            cont = true,
            achievement = {id = 20002, criteria = 65649}, 			
            Zamro = true,
            note = L["Bufo Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",	
	    }),		
		[25802260] = ({
            label = L["Dread Ship Vazuvius"],
            cont = true,
            achievement = {id = 20002, criteria = 65650}, 			
            Zamro = true,
            note = L["Dread Ship Vazuvius Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",	
	    }),		
		[61606340] = ({
            label = L["Golganarr"],
            cont = true,
            achievement = {id = 20002, criteria = 65651}, 			
            Zamro = true,
            note = L["Golganarr Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",	
	    }),		
		[29206320] = ({
            label = L["Imperial Python"],
            cont = true,
            achievement = {id = 20002, criteria = 65652}, 			
            Zamro = true,
            note = L["Imperial Python Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",	
	    }),		
		[33149115] = ({
            label = L["Evermaw"],
            cont = true,
            achievement = {id = 20002, criteria = 65653}, 			
            Zamro = true,
            note = L["Evermaw Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",	
	    }),		
		[56603540] = ({
            label = L["Archiereus of Flame"],
            cont = true,
            achievement = {id = 20002, criteria = 65655}, 			
            Zamro = true,
            note = L["Archiereus of Flame Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",	
	    }),		
		[57207640] = ({
            label = L["Watcher Osu"],
            cont = true,
            achievement = {id = 20002, criteria = 65656}, 			
            Zamro = true,
            note = L["Watcher Osu Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",	
	    }),		
		[43202660] = ({
            label = L["Urdur the Cauterizer"],
            cont = true,
            achievement = {id = 20002, criteria = 65657}, 			
            Zamro = true,
            note = L["Urdur the Cauterizer Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",	
	    }),		
		[52408240] = ({
            label = L["Jakur of Ordon"],
            cont = true,
            achievement = {id = 20002, criteria = 65658}, 			
            Zamro = true,
            note = L["Jakur of Ordon Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",	
	    }),		
		[48803700] = ({
            label = L["Flintlord Gairan"],
            cont = true,
            achievement = {id = 20002, criteria = 65659}, 			
            Zamro = true,
            note = L["Flintlord Gairan Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",	
	    }),		
		[60005100] = ({
            label = L["Champion of the Black Flame"],
            cont = true,
            achievement = {id = 20002, criteria = 65660}, 			
            Zamro = true,
            note = L["Champion of the Black Flame Note"],
            pathto = "Interface\\Addons\\"..myname.."\\Icons\\fskull.tga",	
	    }),				
    },
}