local addonName = ...
local L = LibStub("AceLocale-3.0"):NewLocale(addonName, "enUS", true)

if not L then return end

-- The Jade Forest (Treasure)
L["Ancient Pandaren Tea Pot"] = "|cFFFFFFFFAncient Pandaren Tea Pot|r"
L["Ancient Pandaren Tea Pot Note"] = "Contains |cFF9D9D9DAncient Pandaren Tea Pot|r, cost |cFFFFFFFF10 gold.|r"
L["Lucky Pandaren Coin"] = "|cFFFFFFFFLucky Pandaren Coin|r"
L["Lucky Pandaren Coin Note"] = "Contains |cFF9D9D9DLucky Pandaren Coin|r, cost |cFFFFFFFF10 gold.|r"
L["Pandaren Ritual Stone"] = "|cFFFFFFFFPandaren Ritual Stone|r"
L["Pandaren Ritual Stone Note"] = "Contains |cFF9D9D9DPandaren Ritual Stone|r, cost |cFFFFFFFF10 gold.|r"
L["Ship's Locker"] = "|cFFFFFFFFShip's Locker|r"
L["Ship's Locker Note"] = "Contains 11 |cFFFFFFFFBronze|r, chest in the hold of a ship."

L["Order"] = "|cFFFFFFFFOrder of the Cloud Serpent|r"
L["Order Note"] = "Exchange |cFFFFFFFFLesser Charm of Good Fortune|r on reputation."
L["August"] = "|cFFFFFFFFThe August Celestials|r"
L["August Note"] = "Exchange |cFFFFFFFFLesser Charm of Good Fortune|r on reputation."

L["Chest of Supplies"] = "|cFFFFFFFFChest of Supplies|r"
L["Chest of Supplies Note"] = "Contains |cFFFFFFFF10 gold.|r"
L["Offering of Rememberance"] = "|cFFFFFFFFOffering of Rememberance|r"
L["Offering of Rememberance Note"] = "Contains |cFFFFFFFF11 gold.|r"
L["Stash of Gems"] = "|cFFFFFFFFStash of Gems|r"
L["Stash of Gems Note"] = "Contains 50-55 |cFFFFFFFFBronze|r, and |cFFFFFFFF7 gold.|r"
L["Ancient Pandaren Mining Pick"] = "|cFFFFFFFFAncient Pandaren Mining Pick|r"
L["Ancient Pandaren Mining Pick Note"] = "Contains 50-55 |cFFFFFFFFBronze|r, and |cFFFFFFFF7 gold.|r"

-- The Jade Forest (Rare)
L["Kor'nas Nightsavage"] = "|cFFFFFFFFKor'nas Nightsavage|r"
L["Kor'nas Nightsavage Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Krax'ik"] = "|cFFFFFFFFKrax'ik|r"
L["Krax'ik Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Sarnak"] = "|cFFFFFFFFSarnak|r"
L["Sarnak Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Mister Ferocious"] = "|cFFFFFFFFMister Ferocious|r"
L["Mister Ferocious Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Morgrinn Crackfang"] = "|cFFFFFFFFMorgrinn Crackfang|r"
L["Morgrinn Crackfang Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Aethis"] = "|cFFFFFFFFAethis|r"
L["Aethis Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Urobi the Walker"] = "|cFFFFFFFFUrobi the Walker|r"
L["Urobi the Walker Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Ferdinand"] = "|cFFFFFFFFFerdinand|r"
L["Ferdinand Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."

-- Valley of the Four Winds (Treasure)
L["Virmen Treasure Cache"] = "|cFFFFFFFFVirmen Treasure Cache|r"
L["Virmen Treasure Cache Note"] = "Contains 17 |cFFFFFFFFBronze|r, chest in the hole."
L["The Hammer of Folly"] = "|cFFFFFFFFThe Hammer of Folly|r"
L["The Hammer of Folly Note"] = "Contains |cFF9D9D9DThe Hammer of Folly|r, cost |cFFFFFFFF100 gold.|r"

-- Valley of the Four Winds (Rare)
L["Blackhoof"] = "|cFFFFFFFFBlackhoof|r"
L["Blackhoof Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Jonn-Dar"] = "|cFFFFFFFFJonn-Dar|r"
L["Jonn-Dar Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Nasra Spothide"] = "|cFFFFFFFFNasra Spothide|r"
L["Nasra Spothide Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Sele'na"] = "|cFFFFFFFFSele'na|r"
L["Sele'na Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Bonobos"] = "|cFFFFFFFFBonobos|r"
L["Bonobos Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Nal'lak the Ripper"] = "|cFFFFFFFFNal'lak the Ripper|r"
L["Nal'lak the Ripper Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Salyin Warscout"] = "|cFFFFFFFFSalyin Warscout|r"
L["Salyin Warscout Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Sulik'shor"] = "|cFFFFFFFFSulik'shor|r"
L["Sulik'shor Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."

-- Kun-Lai Summit (Treasure)
L["Hozen Treasure Cache"] = "|cFFFFFFFFHozen Treasure Cache|r"
L["Hozen Treasure Cache Note"] = "Contains 11 |cFFFFFFFFBronze|r, chest in a cave."
L["Stolen Sprite Treasure"] = "|cFFFFFFFFStolen Sprite Treasure|r"
L["Stolen Sprite Treasure Note"] = "Contains 11 |cFFFFFFFFBronze|r, chest in a cave."
L["Statue of Xuen"] = "|cFFFFFFFFStatue of Xuen|r"
L["Statue of Xuen Note"] = "Contains |cFF9D9D9DStatue of Xuen|r, cost |cFFFFFFFF100 gold.|r"
L["Lost Adventurer's Belongings"] = "|cFFFFFFFFLost Adventurer's Belongings|r"
L["Lost Adventurer's Belongings Note"] = "Contains 30-40 |cFFFFFFFFBronze|r."
L["Rikktik's Tiny Chest"] = "|cFFFFFFFFRikktik's Tiny Chest|r"
L["Rikktik's Tiny Chest Note"] = "Contains |cFF9D9D9DRikktik's Tiny Chest|r, cost |cFFFFFFFF105 gold|r and |cFFFFFFFFBronze.|r"
L["Ancient Mogu Tablet"] = "|cFFFFFFFFAncient Mogu Tablet|r"
L["Ancient Mogu Tablet Note"] = "Contains |cFF9D9D9DAncient Mogu Tablet|r, cost |cFFFFFFFF95 gold|r, chest in a cave."
L["Terracotta Head"] = "|cFFFFFFFFTerracotta Head|r"
L["Terracotta Head Note"] = "Contains |cFF9D9D9DTerracotta Head|r, cost |cFFFFFFFF100 gold.|r"

-- Kun-Lai Summit (Rare)
L["Ahone the Wanderer"] = "|cFFFFFFFFAhone the Wanderer|r"
L["Ahone the Wanderer Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Havak"] = "|cFFFFFFFFHavak|r"
L["Havak Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Nessos the Oracle"] = "|cFFFFFFFFNessos the Oracle|r"
L["Nessos the Oracle Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Ski'thik"] = "|cFFFFFFFFSki'thik|r"
L["Ski'thik Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Borginn Darkfist"] = "|cFFFFFFFFBorginn Darkfist|r"
L["Borginn Darkfist Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Korda Torros"] = "|cFFFFFFFFKorda Torros|r"
L["Korda Torros Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Scritch"] = "|cFFFFFFFFScritch|r"
L["Scritch Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Zai the Outcast"] = "|cFFFFFFFFZai the Outcast|r"
L["Zai the Outcast Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."

-- Townlong Steppes (Treasure)
L["Fragment of Dread"] = "|cFFFFFFFFFragment of Dread|r"
L["Fragment of Dread Note"] = "Contains |cFF9D9D9DFragment of Dread|r, cost |cFFFFFFFF90 gold|r, chest in a cave."
L["Hardened Sap of Kri'vess"] = "|cFFFFFFFFHardened Sap of Kri'vess|r"
L["Hardened Sap of Kri'vess Note"] = "Contains |cFF9D9D9DHardened Sap of Kri'vess|r, cost |cFFFFFFFF110 gold.|r."
L["Amber Encased Moth"] = "|cFFFFFFFFAmber Encased Moth|r"
L["Amber Encased Moth Note"] = "Contains |cFF9D9D9DAmber Encased Moth|r, cost |cFFFFFFFF105 gold.|r."
L["Abandoned Crate of Goods"] = "|cFFFFFFFFAbandoned Crate of Goods|r"
L["Abandoned Crate of Goods Note"] = "Contains 40-50 |cFFFFFFFFBronze|r, chest under awning."

L["Shado"] = "|cFFFFFFFFShado-Pan|r"
L["Shado Note"] = "Exchange |cFFFFFFFFLesser Charm of Good Fortune|r on reputation."

-- Townlong Steppes (Rare)
L["The Yowler"] = "|cFFFFFFFFThe Yowler|r"
L["The Yowler Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Lith'ik the Stalker"] = "|cFFFFFFFFLith'ik the Stalker|r"
L["Lith'ik the Stalker Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Kah'tir"] = "|cFFFFFFFFKah'tir|r"
L["Kah'tir Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Siltriss the Sharpener"] = "|cFFFFFFFFSiltriss the Sharpener|r"
L["Siltriss the Sharpener Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Eshelon"] = "|cFFFFFFFFEshelon|r"
L["Eshelon Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Norlaxx"] = "|cFFFFFFFFNorlaxx|r"
L["Norlaxx Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Yul Wildpaw"] = "|cFFFFFFFFYul Wildpaw|r"
L["Yul Wildpaw Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Lon the Bull"] = "|cFFFFFFFFLon the Bull|r"
L["Lon the Bull Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Huggalon the Heart Watcher"] = "|cFFFFFFFFHuggalon the Heart Watcher|r"
L["Huggalon the Heart Watcher Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."

-- Vale of Eternal Blossoms (Rare)
L["Major Nanners"] = "|cFFFFFFFFMajor Nanners|r"
L["Major Nanners Note"] = "Contains 50-60 |cFFFFFFFFBronze|r."
L["Kal'tik the Blight"] = "|cFFFFFFFFKal'tik the Blight|r"
L["Kal'tik the Blight Note"] = "Contains 50-60 |cFFFFFFFFBronze|r."
L["Urgolax"] = "|cFFFFFFFFUrgolax|r"
L["Urgolax Note"] = "Contains 50-60 |cFFFFFFFFBronze|r."
L["Moldo One-Eye"] = "|cFFFFFFFFMoldo One-Eye|r"
L["Moldo One-Eye Note"] = "Contains 50-60 |cFFFFFFFFBronze|r."
L["Sahn Tidehunter"] = "|cFFFFFFFFSahn Tidehunter|r"
L["Sahn Tidehunter Note"] = "Contains 50-60 |cFFFFFFFFBronze|r."
L["Kang the Soul Thief"] = "|cFFFFFFFFKang the Soul Thief|r"
L["Kang the Soul Thief Note"] = "Contains 50-60 |cFFFFFFFFBronze|r."
L["Ai-Ran the Shifting Cloud"] = "|cFFFFFFFFAi-Ran the Shifting Cloud|r"
L["Ai-Ran the Shifting Cloud Note"] = "Contains 50-60 |cFFFFFFFFBronze|r."
L["Yorik Sharpeye"] = "|cFFFFFFFFYorik Sharpeye|r"
L["Yorik Sharpeye Note"] = "Contains 50-60 |cFFFFFFFFBronze|r."
L["Aetha"] = "|cFFFFFFFFAetha|r"
L["Aetha Note"] = "Contains 50-60 |cFFFFFFFFBronze|r."
L["Bai-Jin the Butcher"] = "|cFFFFFFFFBai-Jin the Butcher|r"
L["Bai-Jin the Butcher Note"] = "Contains 50-60 |cFFFFFFFFBronze|r."
L["Baolai the Immolator"] = "|cFFFFFFFFBaolai the Immolator|r"
L["Baolai the Immolator Note"] = "Contains 50-60 |cFFFFFFFFBronze|r."
L["Bloodtip"] = "|cFFFFFFFFBloodtip|r"
L["Bloodtip Note"] = "Contains 50-60 |cFFFFFFFFBronze|r."
L["Huo-Shang"] = "|cFFFFFFFFHuo-Shang|r"
L["Huo-Shang Note"] = "Contains 50-60 |cFFFFFFFFBronze|r."
L["Gaohun the Soul-Severer"] = "|cFFFFFFFFGaohun the Soul-Severer|r"
L["Gaohun the Soul-Severer Note"] = "Contains 50-60 |cFFFFFFFFBronze|r."
L["Cracklefang"] = "|cFFFFFFFFCracklefang|r"
L["Cracklefang Note"] = "Contains 50-60 |cFFFFFFFFBronze|r."
L["General Temuja"] = "|cFFFFFFFFGeneral Temuja|r"
L["General Temuja Note"] = "Contains 50-60 |cFFFFFFFFBronze|r."
L["Gochao the Ironfist"] = "|cFFFFFFFFGochao the Ironfist|r"
L["Gochao the Ironfist Note"] = "Contains 50-60 |cFFFFFFFFBronze|r."
L["Kri'chon"] = "|cFFFFFFFFKri'chon|r"
L["Kri'chon Note"] = "Contains 50-60 |cFFFFFFFFBronze|r."
L["Quid"] = "|cFFFFFFFFQuid|r"
L["Quid Note"] = "Contains 50-60 |cFFFFFFFFBronze|r."
L["Shadowmaster Sydow"] = "|cFFFFFFFFShadowmaster Sydow|r"
L["Shadowmaster Sydow Note"] = "Contains 50-60 |cFFFFFFFFBronze|r."
L["Spirit of Lao-Fe"] = "|cFFFFFFFFSpirit of Lao-Fe|r"
L["Spirit of Lao-Fe Note"] = "Contains 50-60 |cFFFFFFFFBronze|r."
L["Vicejaw"] = "|cFFFFFFFFVicejaw|r"
L["Vicejaw Note"] = "Contains 50-60 |cFFFFFFFFBronze|r."
L["Vyraxxis"] = "|cFFFFFFFFVyraxxis|r"
L["Vyraxxis Note"] = "Contains 50-60 |cFFFFFFFFBronze|r."
L["Wulon"] = "|cFFFFFFFFWulon|r"
L["Wulon Note"] = "Contains 50-60 |cFFFFFFFFBronze|r."

L["Lotus"] = "|cFFFFFFFFGolden Lotus|r"
L["Lotus Note"] = "Exchange |cFFFFFFFFLesser Charm of Good Fortune|r on reputation."

-- Krasarang Wilds (Treasure)
L["Saurok Stone Tablet"] = "|cFFFFFFFFSaurok Stone Tablet|r"
L["Saurok Stone Tablet Note"] = "Contains |cFF9D9D9DSaurok Stone Tablet|r, cost |cFFFFFFFF100 gold.|r."

L["Anglers"] = "|cFFFFFFFFThe Anglers|r"
L["Anglers Note"] = "Exchange |cFFFFFFFFLesser Charm of Good Fortune|r on reputation."
L["Alliance"] = "|cFFFFFFFFAlliance|r"
L["Alliance Note"] = "Exchange |cFFFFFFFFLesser Charm of Good Fortune|r on reputation."
L["Horde"] = "|cFFFFFFFFHorde|r"
L["Horde Note"] = "Exchange |cFFFFFFFFLesser Charm of Good Fortune|r on reputation."

-- Krasarang Wilds (Rare)
L["Arness the Scale"] = "|cFFFFFFFFArness the Scale|r"
L["Arness the Scale Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Gaarn the Toxic"] = "|cFFFFFFFFGaarn the Toxic|r"
L["Gaarn the Toxic Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Qu'nas"] = "|cFFFFFFFFQu'nas|r"
L["Qu'nas Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Spriggin"] = "|cFFFFFFFFSpriggin|r"
L["Spriggin Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Cournith Waterstrider"] = "|cFFFFFFFFCournith Waterstrider|r"
L["Cournith Waterstrider Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Go-Kan"] = "|cFFFFFFFFGo-Kan|r"
L["Go-Kan Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Ruun Ghostpaw"] = "|cFFFFFFFFRuun Ghostpaw|r"
L["Ruun Ghostpaw Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Torik-Ethis"] = "|cFFFFFFFFTorik-Ethis|r"
L["Torik-Ethis Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."

L["Dalan Nightbreaker"] = "|cFFFFFFFFDalan Nightbreaker|r"
L["Dalan Nightbreaker Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Disha Fearwarden"] = "|cFFFFFFFFDisha Fearwarden|r"
L["Disha Fearwarden Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Kar Warmaker"] = "|cFFFFFFFFKar Warmaker|r"
L["Kar Warmaker Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Mavis Harms"] = "|cFFFFFFFFMavis Harms|r"
L["Mavis Harms Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Muerta"] = "|cFFFFFFFFMuerta|r"
L["Muerta Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Ubunti the Shade"] = "|cFFFFFFFFUbunti the Shade|r"
L["Ubunti the Shade Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."

-- Dread Wastes (Rare)
L["Ik-Ik the Nimble"] = "|cFFFFFFFFIk-Ik the Nimble|r"
L["Ik-Ik the Nimble Note"] = "Contains 60-80 |cFFFFFFFFBronze|r."
L["Gar'lok"] = "|cFFFFFFFFGar'lok|r"
L["Gar'lok Note"] = "Contains 60-80 |cFFFFFFFFBronze|r."
L["Krol the Blade"] = "|cFFFFFFFFKrol the Blade|r"
L["Krol the Blade Note"] = "Contains 60-80 |cFFFFFFFFBronze|r."
L["Omnis Grinlok"] = "|cFFFFFFFFOmnis Grinlok|r"
L["Omnis Grinlok Note"] = "Contains 60-80 |cFFFFFFFFBronze|r."
L["Nalash Verdantis"] = "|cFFFFFFFFNalash Verdantis|r"
L["Nalash Verdantis Note"] = "Contains 60-80 |cFFFFFFFFBronze|r."
L["Karr the Darkener"] = "|cFFFFFFFFKarr the Darkener|r"
L["Karr the Darkener Note"] = "Contains 60-80 |cFFFFFFFFBronze|r."
L["Ai-Li Skymirror"] = "|cFFFFFFFFAi-Li Skymirror|r"
L["Ai-Li Skymirror Note"] = "Contains 60-80 |cFFFFFFFFBronze|r."
L["Dak the Breaker"] = "|cFFFFFFFFDak the Breaker|r"
L["Dak the Breaker Note"] = "Contains 60-80 |cFFFFFFFFBronze|r."
L["Zandalari Warbringer"] = "|cFFFFFFFFZandalari Warbringer|r"
L["Zandalari Warbringer Note"] = "Contains 60-80 |cFFFFFFFFBronze|r."

L["Klaxxi"] = "|cFFFFFFFFThe Klaxxi|r"
L["Klaxxi Note"] = "Exchange |cFFFFFFFFLesser Charm of Good Fortune|r on reputation."

-- Isle of Thunder (Rare)
L["Ra'sha"] = "|cFFFFFFFFRa'sha|r"
L["Ra'sha Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["God-Hulk Ramuk"] = "|cFFFFFFFFGod-Hulk Ramuk|r"
L["God-Hulk Ramuk Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Goda"] = "|cFFFFFFFFGoda|r"
L["Goda Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Backbreaker Uru"] = "|cFFFFFFFFBackbreaker Uru|r"
L["Backbreaker Uru Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Lu-Ban"] = "|cFFFFFFFFLu-Ban|r"
L["Lu-Ban Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Mumta"] = "|cFFFFFFFFMumta|r"
L["Mumta Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Progenitus"] = "|cFFFFFFFFProgenitus|r"
L["Progenitus Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Ku'lai the Skyclaw"] = "|cFFFFFFFFKu'lai the Skyclaw|r"
L["Ku'lai the Skyclaw Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Al'tabim the All-Seeing"] = "|cFFFFFFFFAl'tabim the All-Seeing|r"
L["Al'tabim the All-Seeing Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Molthor"] = "|cFFFFFFFFMolthor|r"
L["Molthor Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Haywire Sunreaver Construct"] = "|cFFFFFFFFHaywire Sunreaver Construct|r"
L["Haywire Sunreaver Construct Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."

-- Timeless Isle (Treasure)
L["Flameheart Shawl"] = "|cFFFFFFFFFlameheart Shawl|r"
L["Flameheart Shawl Note"] = "Contains 10-20 |cFFFFFFFFTimeless Coin|r."
L["Riverspeaker's Trident"] = "|cFFFFFFFFRiverspeaker's Trident|r"
L["Riverspeaker's Trident Note"] = "Contains 10-20 |cFFFFFFFFTimeless Coin|r."
L["Cloudstrike Family Helm"] = "|cFFFFFFFFCloudstrike Family Helm|r"
L["Cloudstrike Family Helm Note"] = "Contains 10-20 |cFFFFFFFFTimeless Coin|r."
L["Snowdrift Tiger Talons"] = "|cFFFFFFFFSnowdrift Tiger Talons|r"
L["Snowdrift Tiger Talons Note"] = "Contains 10-20 |cFFFFFFFFTimeless Coin|r."
L["Gleaming Treasure Chest"] = "|cFFFFFFFFGleaming Treasure Chest|r"
L["Gleaming Treasure Chest Note"] = "Contains 10-20 |cFFFFFFFFTimeless Coin|r."
L["Rope-Bound Treasure Chest"] = "|cFFFFFFFFRope-Bound Treasure Chest|r"
L["Rope-Bound Treasure Chest Note"] = "Contains 10-20 |cFFFFFFFFTimeless Coin|r."
L["Mist-Covered Treasure Chest"] = "|cFFFFFFFFMist-Covered Treasure Chest|r"
L["Mist-Covered Treasure Chest Note"] = "Contains 10-20 |cFFFFFFFFTimeless Coin|r."
L["Sunken Treasure"] = "|cFFFFFFFFSunken Treasure|r"
L["Sunken Treasure Note"] = "Contains 10-20 |cFFFFFFFFTimeless Coin|r."
L["Blackguard's Jetsam"] = "|cFFFFFFFFBlackguard's Jetsam|r"
L["Blackguard's Jetsam Note"] = "Contains 10-20 |cFFFFFFFFTimeless Coin|r."
L["Gleaming Treasure Satchel"] = "|cFFFFFFFFGleaming Treasure Satchel|r"
L["Gleaming Treasure Satchel Note"] = "Contains 10-20 |cFFFFFFFFTimeless Coin|r."

-- Timeless Isle (Rare)
L["Jadefire"] = "|cFFFFFFFFSpirit of Jadefire|r"
L["Jadefire Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Rattleskew"] = "|cFFFFFFFFRattleskew|r"
L["Rattleskew Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Cranegnasher"] = "|cFFFFFFFFCranegnasher|r"
L["Cranegnasher Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Spelurk"] = "|cFFFFFFFFSpelurk|r"
L["Spelurk Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Cah Silentsky"] = "|cFFFFFFFFCah Silentsky|r"
L["Cah Silentsky Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Chelon"] = "|cFFFFFFFFChelon|r"
L["Chelon Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Karkanos"] = "|cFFFFFFFFKarkanos|r"
L["Karkanos Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Zhu-Gon the Sour"] = "|cFFFFFFFFZhu-Gon the Sour|r"
L["Zhu-Gon the Sour Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Gu'chi the Swarmbringer"] = "|cFFFFFFFFGu'chi the Swarmbringer|r"
L["Gu'chi the Swarmbringer Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Zesqua"] = "|cFFFFFFFFZesqua|r"
L["Zesqua Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Emerald Gander"] = "|cFFFFFFFFEmerald Gander|r"
L["Emerald Gander Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Great Turtle Furyshell"] = "|cFFFFFFFFGreat Turtle Furyshell|r"
L["Great Turtle Furyshell Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Leafmender"] = "|cFFFFFFFFLeafmender|r"
L["Leafmender Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Ironfur Steelhorn"] = "|cFFFFFFFFIronfur Steelhorn|r"
L["Ironfur Steelhorn Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."

L["Rock Moss"] = "|cFFFFFFFFRock Moss|r"
L["Rock Moss Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Cinderfall"] = "|cFFFFFFFFCinderfall|r"
L["Cinderfall Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Stinkbraid"] = "|cFFFFFFFFStinkbraid|r"
L["Stinkbraid Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Garnia"] = "|cFFFFFFFFGarnia|r"
L["Garnia Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Tsavo'ka"] = "|cFFFFFFFFTsavo'ka|r"
L["Tsavo'ka Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Huolon"] = "|cFFFFFFFFHuolon|r"
L["Huolon Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Monstrous Spineclaw"] = "|cFFFFFFFFMonstrous Spineclaw|r"
L["Monstrous Spineclaw Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Bufo"] = "|cFFFFFFFFBufo|r"
L["Bufo Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Dread Ship Vazuvius"] = "|cFFFFFFFFDread Ship Vazuvius|r"
L["Dread Ship Vazuvius Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Golganarr"] = "|cFFFFFFFFGolganarr|r"
L["Golganarr Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Imperial Python"] = "|cFFFFFFFFImperial Python|r"
L["Imperial Python Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Evermaw"] = "|cFFFFFFFFEvermaw|r"
L["Evermaw Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Archiereus of Flame"] = "|cFFFFFFFFArchiereus of Flame|r"
L["Archiereus of Flame Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Watcher Osu"] = "|cFFFFFFFFWatcher Osu|r"
L["Watcher Osu Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Urdur the Cauterizer"] = "|cFFFFFFFFUrdur the Cauterizer|r"
L["Urdur the Cauterizer Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Jakur of Ordon"] = "|cFFFFFFFFJakur of Ordon|r"
L["Jakur of Ordon Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Flintlord Gairan"] = "|cFFFFFFFFFlintlord Gairan|r"
L["Flintlord Gairan Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."
L["Champion of the Black Flame"] = "|cFFFFFFFFChampion of the Black Flame|r"
L["Champion of the Black Flame Note"] = "Contains 50-70 |cFFFFFFFFBronze|r."

-- Waypoints
L["Create waypoint"] = true
L["Create all waypoints"] = true
L["Hide node"] = true
L["Close"] = true

-- Options
L["Icon settings"] = true
L["These settings control the look of the icon."] = true
L["Icon Scale"] = true
L["The scale of the icons"] = true
L["Icon Alpha"] = true
L["The alpha transparency of the icons"] = true
L["World Map"] = true
L["Show icons on world map"] = true
L["Minimap"] = true
L["Show icons on the minimap"] = true
L["What to display"] = true
L["Show Zamros"] = "Show gold farming locations"
L["Show Zamros gold"] = "Show activity points with which you can earn gold"
L["Reset hidden nodes"] = true
L["Show all nodes that you manually hid by right-clicking on them and choosing \"hide\"."] = true