local myaddon = ...
local L = LibStub("AceLocale-3.0"):NewLocale(myaddon, "ruRU", false)

if not L then return end

-- The Jade Forest (Treasure)
L["Ancient Pandaren Tea Pot"] = "|cFFFFFFFFДревний пандаренский чайник|r"
L["Ancient Pandaren Tea Pot Note"] = "Содержит |cFF9D9D9DДревний пандаренский чайник|r, стоимостью |cFFFFFFFF10 золотых.|r"
L["Lucky Pandaren Coin"] = "|cFFFFFFFFСчастливая пандаренская монетка|r"
L["Lucky Pandaren Coin Note"] = "Содержит |cFF9D9D9DСчастливая пандаренская монетка|r, стоимостью |cFFFFFFFF10 золотых.|r"
L["Pandaren Ritual Stone"] = "|cFFFFFFFFПандаренский ритуальный камень|r"
L["Pandaren Ritual Stone Note"] = "Содержит |cFF9D9D9DПандаренский ритуальный камень|r, стоимостью |cFFFFFFFF10 золотых.|r"
L["Ship's Locker"] = "|cFFFFFFFFКорабельный сейф|r"
L["Ship's Locker Note"] = "Содержит 11 |cFFFFFFFFБронзы|r, сундук в трюме корабля."

L["Order"] = "|cFFFFFFFFОрден Облачного Змея|r"
L["Order Note"] = "Обмен |cFFFFFFFFМалый амулет удачи|r на репутацию."
L["August"] = "|cFFFFFFFFНебожители|r"
L["August Note"] = "Обмен |cFFFFFFFFМалый амулет удачи|r на репутацию."

L["Chest of Supplies"] = "|cFFFFFFFFЯщик с припасами|r"
L["Chest of Supplies Note"] = "Содержит |cFFFFFFFF10 золотых.|r"
L["Offering of Rememberance"] = "|cFFFFFFFFПамятный дар|r"
L["Offering of Rememberance Note"] = "Содержит |cFFFFFFFF11 золотых.|r"
L["Stash of Gems"] = "|cFFFFFFFFСундук с драгоценностями|r"
L["Stash of Gems Note"] = "Содержит 50-55 |cFFFFFFFFБронзы|r, и |cFFFFFFFF7 золотых.|r"
L["Ancient Pandaren Mining Pick"] = "|cFFFFFFFFДревняя пандаренская кирка|r"
L["Ancient Pandaren Mining Pick Note"] = "Содержит 50-55 |cFFFFFFFFБронзы|r, и |cFFFFFFFF7 золотых.|r"

-- The Jade Forest (Rare)
L["Kor'nas Nightsavage"] = "|cFFFFFFFFКор'нас Ночной Изверг|r"
L["Kor'nas Nightsavage Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Krax'ik"] = "|cFFFFFFFFКракс'ик|r"
L["Krax'ik Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Sarnak"] = "|cFFFFFFFFСарнак|r"
L["Sarnak Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Mister Ferocious"] = "|cFFFFFFFFМистер Лютый|r"
L["Mister Ferocious Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Morgrinn Crackfang"] = "|cFFFFFFFFМоргринн Треснувший Клык|r"
L["Morgrinn Crackfang Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Aethis"] = "|cFFFFFFFFЭтис|r"
L["Aethis Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Urobi the Walker"] = "|cFFFFFFFFСтранствующий Уроби|r"
L["Urobi the Walker Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Ferdinand"] = "|cFFFFFFFFЭтис|r"
L["Ferdinand Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."

-- Valley of the Four Winds (Treasure)
L["Virmen Treasure Cache"] = "|cFFFFFFFFСундук с сокровищами гну-синей|r"
L["Virmen Treasure Cache Note"] = "Содержит 17 |cFFFFFFFFБронзы|r, сундук в норе."
L["The Hammer of Folly"] = "|cFFFFFFFFМолот безрассудства|r"
L["The Hammer of Folly Note"] = "Содержит |cFF9D9D9DМолот безрассудства|r, стоимостью |cFFFFFFFF100 золотых.|r"

-- Valley of the Four Winds (Rare)
L["Blackhoof"] = "|cFFFFFFFFЧерное Копыто|r"
L["Blackhoof Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Jonn-Dar"] = "|cFFFFFFFFДжон-Дар|r"
L["Jonn-Dar Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Nasra Spothide"] = "|cFFFFFFFFНашра Пятнистая Шкура|r"
L["Nasra Spothide Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Sele'na"] = "|cFFFFFFFFСеле'на|r"
L["Sele'na Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Bonobos"] = "|cFFFFFFFFБонобос|r"
L["Bonobos Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Nal'lak the Ripper"] = "|cFFFFFFFFНал'лак Раздиратель|r"
L["Nal'lak the Ripper Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Salyin Warscout"] = "|cFFFFFFFFСальинь-разведчик|r"
L["Salyin Warscout Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Sulik'shor"] = "|cFFFFFFFFСулик'шор|r"
L["Sulik'shor Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."

-- Kun-Lai Summit (Treasure)
L["Hozen Treasure Cache"] = "|cFFFFFFFFТайник хозенов|r"
L["Hozen Treasure Cache Note"] = "Содержит 11 |cFFFFFFFFБронзы|r, сундук в пещере."
L["Stolen Sprite Treasure"] = "|cFFFFFFFFУкраденные сокровища духов|r"
L["Stolen Sprite Treasure Note"] = "Содержит 11 |cFFFFFFFFБронзы|r, сундук в пещере."
L["Statue of Xuen"] = "|cFFFFFFFFСтатуя Сюэня|r"
L["Statue of Xuen Note"] = "Содержит |cFF9D9D9DСтатуя Сюэня|r, стоимостью |cFFFFFFFF100 золотых.|r"
L["Lost Adventurer's Belongings"] = "|cFFFFFFFFПотерянные вещи путешественника|r"
L["Lost Adventurer's Belongings Note"] = "Содержит 30-40 |cFFFFFFFFБронзы|r."
L["Rikktik's Tiny Chest"] = "|cFFFFFFFFСундучок Рикктика|r"
L["Rikktik's Tiny Chest Note"] = "Содержит |cFF9D9D9DКлещебойка Рикктика|r, стоимостью |cFFFFFFFF105 золотых.|r и 30-40 |cFFFFFFFFБронзы.|r"
L["Ancient Mogu Tablet"] = "|cFFFFFFFFДревняя табличка могу|r"
L["Ancient Mogu Tablet Note"] = "Содержит |cFF9D9D9DДревняя табличка могу|r, стоимостью |cFFFFFFFF95 золотых.|r Сундук в пещере."
L["Terracotta Head"] = "|cFFFFFFFFГолова из терракоты|r"
L["Terracotta Head Note"] = "Содержит |cFF9D9D9DГолова из терракоты|r, стоимостью |cFFFFFFFF100 золотых.|r"

-- Kun-Lai Summit (Rare)
L["Ahone the Wanderer"] = "|cFFFFFFFFАхон Странствующая|r"
L["Ahone the Wanderer Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Havak"] = "|cFFFFFFFFХавак|r"
L["Havak Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Nessos the Oracle"] = "|cFFFFFFFFНессос Прозорливый|r"
L["Nessos the Oracle Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Ski'thik"] = "|cFFFFFFFFСки'тик|r"
L["Ski'thik Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Borginn Darkfist"] = "|cFFFFFFFFБорджинн Кулак Тьмы|r"
L["Borginn Darkfist Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Korda Torros"] = "|cFFFFFFFFКорда Торрос|r"
L["Korda Torros Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Scritch"] = "|cFFFFFFFFШкряб|r"
L["Scritch Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Zai the Outcast"] = "|cFFFFFFFFЗей Изгой|r"
L["Zai the Outcast Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."

-- Townlong Steppes (Treasure)
L["Fragment of Dread"] = "|cFFFFFFFFФрагмент Ужаса|r"
L["Fragment of Dread Note"] = "Содержит |cFF9D9D9DФрагмент Ужаса|r, стоимостью |cFFFFFFFF90 золотых.|r Сундук в пещере."
L["Hardened Sap of Kri'vess"] = "|cFFFFFFFFЗагустевший нектар Кри'весса|r"
L["Hardened Sap of Kri'vess Note"] = "Содержит |cFF9D9D9DЗагустевший нектар Кри'весса|r, стоимостью |cFFFFFFFF110 золотых.|r."
L["Amber Encased Moth"] = "|cFFFFFFFFМотылек в янтаре|r"
L["Amber Encased Moth Note"] = "Содержит |cFF9D9D9DМотылек в янтаре|r, стоимостью |cFFFFFFFF105 золотых.|r."
L["Abandoned Crate of Goods"] = "|cFFFFFFFFБрошенный ящик с товарами|r"
L["Abandoned Crate of Goods Note"] = "Содержит 40-50 |cFFFFFFFFБронзы|r, сундук под тентом."

L["Shado"] = "|cFFFFFFFFШадо-Пан|r"
L["Shado Note"] = "Обмен |cFFFFFFFFМалый амулет удачи|r на репутацию."

-- Townlong Steppes (Rare)
L["The Yowler"] = "|cFFFFFFFFИзувой|r"
L["The Yowler Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Lith'ik the Stalker"] = "|cFFFFFFFFЛит'ик Охотник|r"
L["Lith'ik the Stalker Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Kah'tir"] = "|cFFFFFFFFКах'тир|r"
L["Kah'tir Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Siltriss the Sharpener"] = "|cFFFFFFFFСилстрисс Точильщик|r"
L["Siltriss the Sharpener Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Eshelon"] = "|cFFFFFFFFИшилон|r"
L["Eshelon Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Norlaxx"] = "|cFFFFFFFFНорлакс|r"
L["Norlaxx Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Yul Wildpaw"] = "|cFFFFFFFFЮл Дикая Лапа|r"
L["Yul Wildpaw Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Lon the Bull"] = "|cFFFFFFFFЛонь Бык|r"
L["Lon the Bull Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Huggalon the Heart Watcher"] = "|cFFFFFFFFХуггалон Смотритель Сердец|r"
L["Huggalon the Heart Watcher Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."

-- Vale of Eternal Blossoms (Rare)
L["Major Nanners"] = "|cFFFFFFFFМайор Наннерс|r"
L["Major Nanners Note"] = "Содержит 50-60 |cFFFFFFFFБронзы|r."
L["Kal'tik the Blight"] = "|cFFFFFFFFКал'тик Болезнетворный|r"
L["Kal'tik the Blight Note"] = "Содержит 50-60 |cFFFFFFFFБронзы|r."
L["Urgolax"] = "|cFFFFFFFFУрголакс|r"
L["Urgolax Note"] = "Содержит 50-60 |cFFFFFFFFБронзы|r."
L["Moldo One-Eye"] = "|cFFFFFFFFМолдо Одноглазый|r"
L["Moldo One-Eye Note"] = "Содержит 50-60 |cFFFFFFFFБронзы|r."
L["Sahn Tidehunter"] = "|cFFFFFFFFСан Охотник Прилива|r"
L["Sahn Tidehunter Note"] = "Содержит 50-60 |cFFFFFFFFБронзы|r."
L["Kang the Soul Thief"] = "|cFFFFFFFFКан Похититель Душ|r"
L["Kang the Soul Thief Note"] = "Содержит 50-60 |cFFFFFFFFБронзы|r."
L["Ai-Ran the Shifting Cloud"] = "|cFFFFFFFFАй-Жань Летящее Облако|r"
L["Ai-Ran the Shifting Cloud Note"] = "Содержит 50-60 |cFFFFFFFFБронзы|r."
L["Yorik Sharpeye"] = "|cFFFFFFFFЙорик Острый Глаз|r"
L["Yorik Sharpeye Note"] = "Содержит 50-60 |cFFFFFFFFБронзы|r."
L["Aetha"] = "|cFFFFFFFFАйта|r"
L["Aetha Note"] = "Содержит 50-60 |cFFFFFFFFБронзы|r."
L["Bai-Jin the Butcher"] = "|cFFFFFFFFБай-Цзинь Мясник|r"
L["Bai-Jin the Butcher Note"] = "Содержит 50-60 |cFFFFFFFFБронзы|r."
L["Baolai the Immolator"] = "|cFFFFFFFFБаолай Воспламенитель|r"
L["Baolai the Immolator Note"] = "Содержит 50-60 |cFFFFFFFFБронзы|r."
L["Bloodtip"] = "|cFFFFFFFFКроволапка|r"
L["Bloodtip Note"] = "Содержит 50-60 |cFFFFFFFFБронзы|r."
L["Huo-Shang"] = "|cFFFFFFFFХо-Шуан|r"
L["Huo-Shang Note"] = "Содержит 50-60 |cFFFFFFFFБронзы|r."
L["Gaohun the Soul-Severer"] = "|cFFFFFFFFГаохунь Ловец Душ|r"
L["Gaohun the Soul-Severer Note"] = "Содержит 50-60 |cFFFFFFFFБронзы|r."
L["Cracklefang"] = "|cFFFFFFFFХрустозуб|r"
L["Cracklefang Note"] = "Содержит 50-60 |cFFFFFFFFБронзы|r."
L["General Temuja"] = "|cFFFFFFFFГенерал Темуджа|r"
L["General Temuja Note"] = "Содержит 50-60 |cFFFFFFFFБронзы|r."
L["Gochao the Ironfist"] = "|cFFFFFFFFГочао Железный Кулак|r"
L["Gochao the Ironfist Note"] = "Содержит 50-60 |cFFFFFFFFБронзы|r."
L["Kri'chon"] = "|cFFFFFFFFКри'чон|r"
L["Kri'chon Note"] = "Содержит 50-60 |cFFFFFFFFБронзы|r."
L["Quid"] = "|cFFFFFFFFСклизень|r"
L["Quid Note"] = "Содержит 50-60 |cFFFFFFFFБронзы|r."
L["Shadowmaster Sydow"] = "|cFFFFFFFFПовелитель теней Сайдоу|r"
L["Shadowmaster Sydow Note"] = "Содержит 50-60 |cFFFFFFFFБронзы|r."
L["Spirit of Lao-Fe"] = "|cFFFFFFFFДух Лао-Фэ|r"
L["Spirit of Lao-Fe Note"] = "Содержит 50-60 |cFFFFFFFFБронзы|r."
L["Vicejaw"] = "|cFFFFFFFFЗлобнохап|r"
L["Vicejaw Note"] = "Содержит 50-60 |cFFFFFFFFБронзы|r."
L["Vyraxxis"] = "|cFFFFFFFFВираксис|r"
L["Vyraxxis Note"] = "Содержит 50-60 |cFFFFFFFFБронзы|r."
L["Wulon"] = "|cFFFFFFFFУлунь|r"
L["Wulon Note"] = "Содержит 50-60 |cFFFFFFFFБронзы|r."

L["Lotus"] = "|cFFFFFFFFЗолотой Лотос|r"
L["Lotus Note"] = "Обмен |cFFFFFFFFМалый амулет удачи|r на репутацию."

-- Krasarang Wilds (Treasure)
L["Saurok Stone Tablet"] = "|cFFFFFFFFКаменная скрижаль сауроков|r"
L["Saurok Stone Tablet Note"] = "Содержит |cFF9D9D9DКаменная скрижаль сауроков|r, стоимостью |cFFFFFFFF100 золотых.|r."

L["Anglers"] = "|cFFFFFFFFРыболовы|r"
L["Anglers Note"] = "Обмен |cFFFFFFFFМалый амулет удачи|r на репутацию."
L["Alliance"] = "|cFFFFFFFFАльянс|r"
L["Alliance Note"] = "Обмен |cFFFFFFFFМалый амулет удачи|r на репутацию."
L["Horde"] = "|cFFFFFFFFОрда|r"
L["Horde Note"] = "Обмен |cFFFFFFFFМалый амулет удачи|r на репутацию."

-- Krasarang Wilds (Rare)
L["Arness the Scale"] = "|cFFFFFFFFАрнесс Чешуйчатый|r"
L["Arness the Scale Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Gaarn the Toxic"] = "|cFFFFFFFFГаарн Ядовитый|r"
L["Gaarn the Toxic Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Qu'nas"] = "|cFFFFFFFFКу'нас|r"
L["Qu'nas Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Spriggin"] = "|cFFFFFFFFХмызень|r"
L["Spriggin Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Cournith Waterstrider"] = "|cFFFFFFFFКурниф Долгоног|r"
L["Cournith Waterstrider Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Go-Kan"] = "|cFFFFFFFFГо-Кан|r"
L["Go-Kan Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Ruun Ghostpaw"] = "|cFFFFFFFFЖуунь Призрачная Лапа|r"
L["Ruun Ghostpaw Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Torik-Ethis"] = "|cFFFFFFFFТорик-Этис|r"
L["Torik-Ethis Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."

L["Dalan Nightbreaker"] = "|cFFFFFFFFДалан Разрушитель Ночи|r"
L["Dalan Nightbreaker Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Disha Fearwarden"] = "|cFFFFFFFFДиша Защищающая от Страха|r"
L["Disha Fearwarden Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Kar Warmaker"] = "|cFFFFFFFFКар Развязывающий Войну|r"
L["Kar Warmaker Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Mavis Harms"] = "|cFFFFFFFFМавис Хармс|r"
L["Mavis Harms Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Muerta"] = "|cFFFFFFFFМуэрта|r"
L["Muerta Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Ubunti the Shade"] = "|cFFFFFFFFУбунти Тень|r"
L["Ubunti the Shade Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."

-- Dread Wastes (Rare)
L["Ik-Ik the Nimble"] = "|cFFFFFFFFИк-Ик Проворный|r"
L["Ik-Ik the Nimble Note"] = "Содержит 60-80 |cFFFFFFFFБронзы|r."
L["Gar'lok"] = "|cFFFFFFFFГар'лок|r"
L["Gar'lok Note"] = "Содержит 60-80 |cFFFFFFFFБронзы|r."
L["Krol the Blade"] = "|cFFFFFFFFКрол Клинок|r"
L["Krol the Blade Note"] = "Содержит 60-80 |cFFFFFFFFБронзы|r."
L["Omnis Grinlok"] = "|cFFFFFFFFОмнис Гринлок|r"
L["Omnis Grinlok Note"] = "Содержит 60-80 |cFFFFFFFFБронзы|r."
L["Nalash Verdantis"] = "|cFFFFFFFFНалаш Зеленый|r"
L["Nalash Verdantis Note"] = "Содержит 60-80 |cFFFFFFFFБронзы|r."
L["Karr the Darkener"] = "|cFFFFFFFFКарр Несущий Тьму|r"
L["Karr the Darkener Note"] = "Содержит 60-80 |cFFFFFFFFБронзы|r."
L["Ai-Li Skymirror"] = "|cFFFFFFFFАй-Ли Небесное Зеркало|r"
L["Ai-Li Skymirror Note"] = "Содержит 60-80 |cFFFFFFFFБронзы|r."
L["Dak the Breaker"] = "|cFFFFFFFFДак Крушитель|r"
L["Dak the Breaker Note"] = "Содержит 60-80 |cFFFFFFFFБронзы|r."
L["Zandalari Warbringer"] = "|cFFFFFFFFЗандаларский завоеватель|r"
L["Zandalari Warbringer Note"] = "Содержит 60-80 |cFFFFFFFFБронзы|r."

L["Klaxxi"] = "|cFFFFFFFFКлакси|r"
L["Klaxxi Note"] = "Обмен |cFFFFFFFFМалый амулет удачи|r на репутацию."

-- Isle of Thunder (Rare)
L["Ra'sha"] = "|cFFFFFFFFРа'ша|r"
L["Ra'sha Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["God-Hulk Ramuk"] = "|cFFFFFFFFБог-исполин Рамук|r"
L["God-Hulk Ramuk Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Goda"] = "|cFFFFFFFFГода|r"
L["Goda Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Backbreaker Uru"] = "|cFFFFFFFFЛоматель хребтов Уру|r"
L["Backbreaker Uru Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Lu-Ban"] = "|cFFFFFFFFЛю-Бань|r"
L["Lu-Ban Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Mumta"] = "|cFFFFFFFFМумта|r"
L["Mumta Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Progenitus"] = "|cFFFFFFFFПородитель|r"
L["Progenitus Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Ku'lai the Skyclaw"] = "|cFFFFFFFFКу'лаи Коготь Небес|r"
L["Ku'lai the Skyclaw Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Al'tabim the All-Seeing"] = "|cFFFFFFFFАл'табим Всевидящий|r"
L["Al'tabim the All-Seeing Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Molthor"] = "|cFFFFFFFFМолтор|r"
L["Molthor Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Haywire Sunreaver Construct"] = "|cFFFFFFFFВзбешенный голем Похитителей Солнца|r"
L["Haywire Sunreaver Construct Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."

-- Timeless Isle (Treasure)
L["Flameheart Shawl"] = "|cFFFFFFFFШаль пламенного сердца|r"
L["Flameheart Shawl Note"] = "Содержит 10-20 |cFFFFFFFFВневременная монета|r."
L["Riverspeaker's Trident"] = "|cFFFFFFFFТрезубец говорящего с рекой|r"
L["Riverspeaker's Trident Note"] = "Содержит 10-20 |cFFFFFFFFВневременная монета|r."
L["Cloudstrike Family Helm"] = "|cFFFFFFFFФамильный шлем Небесного Удара|r"
L["Cloudstrike Family Helm Note"] = "Содержит 10-20 |cFFFFFFFFВневременная монета|r."
L["Snowdrift Tiger Talons"] = "|cFFFFFFFFКогти снежного тигра|r"
L["Snowdrift Tiger Talons Note"] = "Содержит 10-20 |cFFFFFFFFВневременная монета|r."
L["Gleaming Treasure Chest"] = "|cFFFFFFFFБлестящий сундук с сокровищами|r"
L["Gleaming Treasure Chest Note"] = "Содержит 10-20 |cFFFFFFFFВневременная монета|r."
L["Rope-Bound Treasure Chest"] = "|cFFFFFFFFПеревязанный канатами ящик с сокровищами|r"
L["Rope-Bound Treasure Chest Note"] = "Содержит 10-20 |cFFFFFFFFВневременная монета|r."
L["Mist-Covered Treasure Chest"] = "|cFFFFFFFFОкутанный дымкой сундук с сокровищами|r"
L["Mist-Covered Treasure Chest Note"] = "Содержит 10-20 |cFFFFFFFFВневременная монета|r."
L["Sunken Treasure"] = "|cFFFFFFFFЗатонувшее сокровище|r"
L["Sunken Treasure Note"] = "Содержит 10-20 |cFFFFFFFFВневременная монета|r."
L["Blackguard's Jetsam"] = "|cFFFFFFFFГруз черного стража|r"
L["Blackguard's Jetsam Note"] = "Содержит 10-20 |cFFFFFFFFВневременная монета|r."
L["Gleaming Treasure Satchel"] = "|cFFFFFFFFБлестящий мешок с сокровищами|r"
L["Gleaming Treasure Satchel Note"] = "Содержит 10-20 |cFFFFFFFFВневременная монета|r."

-- Timeless Isle (Rare)
L["Jadefire"] = "|cFFFFFFFFДух Нефритового Пламени|r"
L["Jadefire Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Rattleskew"] = "|cFFFFFFFFКосохрип|r"
L["Rattleskew Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Cranegnasher"] = "|cFFFFFFFFЖуравлецап|r"
L["Cranegnasher Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Spelurk"] = "|cFFFFFFFFЧароброд|r"
L["Spelurk Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Cah Silentsky"] = "|cFFFFFFFFКа Тихое Небо|r"
L["Cah Silentsky Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Chelon"] = "|cFFFFFFFFШелон|r"
L["Chelon Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Karkanos"] = "|cFFFFFFFFКарканос|r"
L["Karkanos Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Zhu-Gon the Sour"] = "|cFFFFFFFFЧжу-Гонь Прокисший|r"
L["Zhu-Gon the Sour Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Gu'chi the Swarmbringer"] = "|cFFFFFFFFГу'чи Зовущий Рой|r"
L["Gu'chi the Swarmbringer Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Zesqua"] = "|cFFFFFFFFЗесква|r"
L["Zesqua Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Emerald Gander"] = "|cFFFFFFFFИзумрудный гусак|r"
L["Emerald Gander Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Great Turtle Furyshell"] = "|cFFFFFFFFБольшая черепаха Гневный Панцирь|r"
L["Great Turtle Furyshell Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Leafmender"] = "|cFFFFFFFFЦелитель листвы|r"
L["Leafmender Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Ironfur Steelhorn"] = "|cFFFFFFFFТвердорогий сталемех|r"
L["Ironfur Steelhorn Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."

L["Rock Moss"] = "|cFFFFFFFFПещерный Мох|r"
L["Rock Moss Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Cinderfall"] = "|cFFFFFFFFПеплопад|r"
L["Cinderfall Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Stinkbraid"] = "|cFFFFFFFFВонекос|r"
L["Stinkbraid Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Garnia"] = "|cFFFFFFFFГарния|r"
L["Garnia Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Tsavo'ka"] = "|cFFFFFFFFТсаво'ка|r"
L["Tsavo'ka Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Huolon"] = "|cFFFFFFFFХолон|r"
L["Huolon Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Monstrous Spineclaw"] = "|cFFFFFFFFОгромный иглохват|r"
L["Monstrous Spineclaw Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Bufo"] = "|cFFFFFFFFБуфо|r"
L["Bufo Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Dread Ship Vazuvius"] = "|cFFFFFFFFПроклятый корабль Вазувий|r"
L["Dread Ship Vazuvius Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Golganarr"] = "|cFFFFFFFFГолганарр|r"
L["Golganarr Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Imperial Python"] = "|cFFFFFFFFИмператорский питон|r"
L["Imperial Python Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Evermaw"] = "|cFFFFFFFFВечножор|r"
L["Evermaw Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Archiereus of Flame"] = "|cFFFFFFFFАрхиерей пламени|r"
L["Archiereus of Flame Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Watcher Osu"] = "|cFFFFFFFFСмотритель Осу|r"
L["Watcher Osu Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Urdur the Cauterizer"] = "|cFFFFFFFFУрдур Прижигатель|r"
L["Urdur the Cauterizer Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Jakur of Ordon"] = "|cFFFFFFFFЯкур Ордосский|r"
L["Jakur of Ordon Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Flintlord Gairan"] = "|cFFFFFFFFПовелитель кремня Гайран|r"
L["Flintlord Gairan Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."
L["Champion of the Black Flame"] = "|cFFFFFFFFЗащитник Черного Пламени|r"
L["Champion of the Black Flame Note"] = "Содержит 50-70 |cFFFFFFFFБронзы|r."


-- Waypoints
L["Create waypoint"] = "Создать путевую точку"
L["Create all waypoints"] = "Создать все путевые точки"
L["Hide node"] = "Скрыть точку"
L["Close"] = "Закрыть"

-- Options
L["Icon settings"] = "Настройки Значков"
L["These settings control the look of the icon."] = "Эти настройки управляют внешним видом значка."
L["Icon Scale"] = "Масштаб Значков"
L["The scale of the icons"] = "Масштаб Значков"
L["Icon Alpha"] = "Альфа Значок"
L["The alpha transparency of the icons"] = "Прозрачность значков"
L["World Map"] = "Карта Мира"
L["Show icons on world map"] = "Показать значки на карте мира"
L["Minimap"] = "Мини-карта"
L["Show icons on the minimap"] = "Показать значки на мини-карте"
L["What to display"] = "Что отображать"
L["Show Zamros"] = "Показать места фарма золота"
L["Show Zamros gold"] = "Показать точки активностей, с помощью которых можно зарабатывать золото"
L["Reset hidden nodes"] = "Сбросить скрытые точки"
L["Show all nodes that you manually hid by right-clicking on them and choosing \"hide\"."] = "Показать все точки, которые вы вручную скрыли, щелкнув по ним правой кнопкой мыши и выбрав \"скрыть\"."